#buildspec.yaml

version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t php-application-2022 .
      - docker tag php-application-2022:latest 316026101470.dkr.ecr.ap-south-1.amazonaws.com/php-application-2022:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 316026101470.dkr.ecr.ap-south-1.amazonaws.com/php-application-2022:latest
