#buildspec.yaml  

version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 316026101470.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo $pwd
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t php-application-2022 .
      - docker tag php-application-2022:latest 316026101470.dkr.ecr.ap-south-1.amazonaws.com/php-application-2022:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 316026101470.dkr.ecr.ap-south-1.amazonaws.com/php-application-2022:latest
      - echo Writing image definitions file...
      - printf '[{"name":"hello-world","imageUri":"%s"}]' 316026101470.dkr.ecr.ap-south-1.amazonaws.com/php-application-2022:latest > imagedefinitions.json
artifacts:
      files: imagedefinitions.json
