version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...  
      - aws --version
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 814247870303.dkr.ecr.us-west-2.amazonaws.com

      - REPOSITORY_URI=814247870303.dkr.ecr.us-west-2.amazonaws.com/themagic5-test-internal  
      - COMMIT_HASH=$CODEBUILD_RESOLVED_SOURCE_VERSION

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$COMMIT_HASH .
      - docker tag $REPOSITORY_URI:$COMMIT_HASH $REPOSITORY_URI:$COMMIT_HASH
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$COMMIT_HASH
   
      
      - echo Writing image definitions file...
      - printf '[{"name":"themagic5-test-internal","imageUri":"%s"}]' $REPOSITORY_URI:$COMMIT_HASH > themagic5-test-internal-imagedefinitions.json
artifacts:
    files: themagic5-test-internal-imagedefinitions.json
