version: 0.2  

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 316026101470.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t themagic5-test-internal .
      - docker tag themagic5-test-internal:latest 316026101470.dkr.ecr.ap-south-1.amazonaws.com/themagic5-test-internal:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push $IMAGE_REPO_NAME:latest  
      - printf '[{"name":"themagic5-test-internal","imageUri":"%s"}]' $IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION > themagic5-test-internal-imagedefinitions.json
artifacts:
  files:
    - themagic5-test-internal-imagedefinitions.json
